### PR TITLE
fix wrong complete in php

### PR DESCRIPTION
**Pull request by ptcong**
```
$this->model->query()
    [cursor here]->select()->get()
```
When cursor in above position, press `tab` it will complete cdnjs css

### CODE REVIEW

**Comment by ptcong** [comment]
Hey @idleberg why u close this pr ?

**Comment by idleberg** [comment]
I appears to me that this is a problem caused by incorrect usage. There are probably conflicting situations, but I couldn't possibly address all of them. Why do you press <kbd>Tab</kbd> when you don't to complete? You can always press <kbd>Esc</kbd> to avoid the completion shown in the completion pop-up. Likewise, you can always select a different  completion from that pop-up.

If you still think there's reason to exclude an entire scope, meaning that nobody will ever be able to use these completions, please provide some arguments that aren't based on a single case.

**Comment by ptcong** [comment]
Have you ever write php code ?
When u write a long query builder and want to make it look better, just break lines before ->
Like jquery
$(selector).find(sub)[ you want to break line here then press a TAB].addClass(cls).doSomething()

Press tab there to indent, not to get autocomplete and it does not show any suggestion before i press tab.

**Comment by idleberg** [comment]
> Press tab there to indent, not to get autocomplete and it does not show any suggestion before i press tab.

As I've already suspected, your "problem" is rooted in your Sublime Text setup. You should probably adjust your `auto_complete_selector` to display the completion pop-up for the  `embedding.php` scope.

**Comment by ptcong** [comment]
Ok i got it

**Pull request closed without merging**
